# This file is a template, and might need editing before it works on your project.
docker-build-master:
  stage: build
  before_script:
  #  - echo $CI_REGISTRY_USER
  #  - echo $CI_REGISTRY
    # - sudo docker login -u build -p !QAZ2wsx $CI_REGISTRY
  script:
   # - echo $CI_REGISTRY_USER
   # - echo $CI_REGISTRY
    - docker build -t bpm-request-manager .
  #  - sudo docker push "$CI_REGISTRY_IMAGE"
  only:
    - master
  tags:
    - sgpi1
docker-run-master:
  stage: deploy
  script:
    - docker stop $(docker ps -q --filter ancestor=bpm-request-manager)
    - docker run -d -p 3000:80 bpm-request-manager
  allow_failure: true
  only:
    - master
  tags:
    - sgpi1