export const SET_PROCESSES_ID = "SET_PROCESSES_ID";
export const SET_PROCESSES_TASKS = "SET_PROCESSES_TASKS";
export const SET_DRAWER_ACTIVE = "SET_DRAWER_ACTIVE";
export const SET_DRAWER_INACTIVE = "SET_DRAWER_INACTIVE";
export const SET_PROCESSES_DEFINITIONS = "SET_PROCESSES_DEFINITIONS";
export const SET_FORMS_FIELDS = "SET_FORMS_FIELDS";
export const SET_MODAL_ACTIVE = "SET_MODAL_ACTIVE";
export const SET_MODAL_INACTIVE = "SET_MODAL_INACTIVE";



