export const REQUEST_TABLE_DATA = "REQUEST_TABLE_DATA";
export const SET_TABLE_DATA = "SET_TABLE_DATA";
export const TOGGLE_DRAWER_STATUS = "TOGGLE_DRAWER_STATUS";
export const TOGGLE_MODAL_STATUS = "TOGGLE_MODAL_STATUS";
export const SET_DRAWER_OPTIONS = "SET_DRAWER_OPTIONS";
export const SET_FORM_OPTIONS = "SET_FORM_OPTIONS";
export const CLEAR_DATA = "CLEAR_DATA";



